### ISSUE TITLE
Is that still Active ?

### ISSUE THREAD

**Issue by vkuehn** [19hundreds/nextcloud_with_debops#1]
Would it work with the newest version of nextcloud ?

**Comment by drybjed** [comment]
This particular repository seems to be outdated a bit in regards to DebOps itself (for example there's no `bootstrap` role anymore), but it seems to be easy to adapt to the current version of the project.

DebOps keeps up with Nextcloud releases, so by itself it should install the current version just fine.

**Comment by vkuehn** [comment]
thanks for that
